const express = require('express')
const authRoutes = require('./auth.routes')
const homeRoutes = require('./home.routes')
const productRoutes = require('./product.routes')
const contentRoutes = require('./content.routes')
const exposureRoutes = require('./exposure.routes')
const demandRoutes = require('./demand.routes')
const clueRoutes = require('./clue.routes')
const applicationRoutes = require('./application.routes')
const profileRoutes = require('./profile.routes')
const serviceRoutes = require('./service.routes')
const analyticsRoutes = require('./analytics.routes')
const notificationRoutes = require('./notification.routes')
const carsRoutes = require('./cars.routes')
const toolsRoutes = require('./tools.routes')
const channelRoutes = require('./channel.routes')
const intakeRoutes = require('./intake.routes')
const warrantyRoutes = require('./warranty.routes')
const adminRoutes = require('./admin.routes')
const financeCircleRoutes = require('./financeCircle.routes')
const casesRoutes = require('./cases.routes')

const router = express.Router()

router.get('/health', (req, res) => {
  res.json({ code: 0, message: 'ok', data: { service: 'liangye-api' } })
})

router.get('/config/integrations', (req, res) => {
  const { ok } = require('../utils/response')
  const { getPublicIntegrationConfig } = require('../services/integrations.service')
  ok(res, getPublicIntegrationConfig())
})

router.get('/config/trial-version', (req, res) => {
  const { ok } = require('../utils/response')
  const { getTrialVersionMeta } = require('../services/trial-version.service')
  ok(res, getTrialVersionMeta())
})

router.use('/auth', authRoutes)
router.use('/home', homeRoutes)
router.use('/products', productRoutes)
router.use('/content', contentRoutes)
router.use('/exposure', exposureRoutes)
router.use('/demands', demandRoutes)
router.use('/clues', clueRoutes)
router.use('/applications', applicationRoutes)
router.use('/profile', profileRoutes)
router.use('/service', serviceRoutes)
router.use('/analytics', analyticsRoutes)
router.use('/notifications', notificationRoutes)
router.use('/cars', carsRoutes)
router.use('/tools', toolsRoutes)
router.use('/channels', channelRoutes)
router.use('/intake', intakeRoutes)
router.use('/warranty', warrantyRoutes)
router.use('/finance-circle', financeCircleRoutes)
router.use('/cases', casesRoutes)
router.use('/admin', adminRoutes)

module.exports = router
